<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Version>2.0.0</Version>
    <Description>Rzs Serilog</Description>

    <PackageLicenseUrl></PackageLicenseUrl>

    <Authors>room-zero-solutions</Authors>
    <Company>room-zero-solutions</Company>

    <PackageReleaseNotes></PackageReleaseNotes>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <PackageProjectUrl>https://github.com/room-zero-solutions/rzs-external--serilog</PackageProjectUrl>
    <RepositoryUrl>https://github.com/room-zero-solutions/rzs-external--serilog</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <IncludeSymbols>false</IncludeSymbols>

    <PackageId>RzsSerilog</PackageId>
    <Product>RzsSerilog</Product>
    <RootNamespace>RzsSerilog</RootNamespace>
    <AssemblyName>RzsSerilog</AssemblyName>

    <Nullable>enable</Nullable>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <AnalysisLevel>5.0</AnalysisLevel>
    <AnalysisMode>AllEnabledByDefault</AnalysisMode>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
	
	<RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MurmurHash-net-core" />
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="Serilog.Enrichers.AspNetCore" />
    <PackageReference Include="Serilog.Enrichers.ClientInfo" />
    <PackageReference Include="Serilog.Enrichers.Context" />
    <PackageReference Include="Serilog.Enrichers.Environment" />
    <PackageReference Include="Serilog.Enrichers.Thread" />
    <PackageReference Include="Serilog.Exceptions" />
    <PackageReference Include="Serilog.Expressions" />
    <PackageReference Include="Serilog.Settings.Configuration" />
    <PackageReference Include="Serilog.Sinks.ApplicationInsights" />
    <PackageReference Include="Serilog.Sinks.Async" />
    <PackageReference Include="Serilog.Sinks.AzureTableStorage" />
    <PackageReference Include="Serilog.Sinks.Console" />
    <PackageReference Include="Serilog.Sinks.File" />
    <PackageReference Include="Serilog.Sinks.Seq" />
    <PackageReference Include="SerilogAnalyzer" />
  </ItemGroup>

</Project>
